name: "build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "x86_64-linux"
          - "aarch64-linux"

    steps:
      - uses: actions/checkout@v4
      # We only run this if we are building an aarch64-linux system
      - if: matrix.machine.platform == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3
      - run: |
          sudo mkdir -p /etc/nix
          echo "machine attic.ergotu.com password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            extra-platforms = aarch64-linux
            substituters = https://attic.ergotu.com/system?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= system:tqRuvHZjHCGH0dWDXShIRPlocnrtZGPbXIhv7AxC+0s= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build and push system
        run: |
          nix build .
          nix run github:zhaofengli/attic#default login ergotu https://attic.ergotu.com ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default push system result
